using System.Globalization;

namespace ogloszenia.Services
{
    public interface ILocalizationService
    {
        string Get(string key, string? language = null);
    }

    public class LocalizationService : ILocalizationService
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["pl"] = new Dictionary<string, string>
            {
                ["Home"] = "Strona główna",
                ["Advertisements"] = "Ogłoszenia",
                ["AddAdvertisement"] = "Dodaj ogłoszenie",
                ["Categories"] = "Kategorie",
                ["Search"] = "Szukaj",
                ["Login"] = "Zaloguj",
                ["Register"] = "Zarejestruj",
                ["Logout"] = "Wyloguj",
                ["Profile"] = "Profil",
                ["AdminPanel"] = "Panel Admina",
                ["Title"] = "Tytuł",
                ["Description"] = "Opis",
                ["Price"] = "Cena",
                ["Category"] = "Kategoria",
                ["CreatedAt"] = "Data dodania",
                ["ViewCount"] = "Odsłon",
                ["Edit"] = "Edytuj",
                ["Delete"] = "Usuń",
                ["Details"] = "Szczegóły",
                ["Save"] = "Zapisz",
                ["Cancel"] = "Anuluj",
                ["Back"] = "Powrót",
                ["Submit"] = "Wyślij",
                ["Username"] = "Nazwa użytkownika",
                ["Email"] = "Email",
                ["Password"] = "Hasło",
                ["ConfirmPassword"] = "Potwierdź hasło",
                ["ForgotPassword"] = "Zapomniałeś hasła?",
                ["ResetPassword"] = "Zresetuj hasło",
                ["ChangePassword"] = "Zmień hasło",
                ["Welcome"] = "Witamy w serwisie ogłoszeń!",
                ["LatestAds"] = "Najnowsze ogłoszenia",
                ["NoResults"] = "Brak wyników",
                ["Loading"] = "Ładowanie...",
                ["Error"] = "Błąd",
                ["Success"] = "Sukces",
                ["Users"] = "Użytkownicy",
                ["Moderation"] = "Moderacja",
                ["Settings"] = "Ustawienia",
                ["Newsletter"] = "Newsletter",
                ["AdminMessage"] = "Wiadomość administratora",
                ["ForbiddenWords"] = "Słowa zakazane",
                ["Theme"] = "Motyw",
                ["Language"] = "Język",
                ["PageSize"] = "Liczba na stronie",
                // Strona główna
                ["ClassifiedsService"] = "Serwis ogłoszeń drobnych",
                ["SearchingOrSelling"] = "Szukasz czegoś? Może chcesz coś sprzedać? Zapraszamy do naszego serwisu!",
                ["SearchAds"] = "Szukaj ogłoszeń...",
                ["BrowseAll"] = "Przeglądaj wszystkie",
                ["EasyAdding"] = "Łatwe dodawanie",
                ["EasyAddingDesc"] = "Dodaj ogłoszenie w zaledwie kilka minut",
                ["FastSearch"] = "Szybkie wyszukiwanie",
                ["FastSearchDesc"] = "Znajdź to co szukasz w sekundach",
                ["CategoriesFeature"] = "Kategorie",
                ["CategoriesDesc"] = "Przejrzane kategorie ogłoszeń",
                ["SecureTransaction"] = "Bezpieczna transakcja",
                ["SecureTransactionDesc"] = "Kontakt bezpośredni ze sprzedawcą",
                ["AdminMessageTitle"] = "Wiadomość od administracji",
                ["NoAds"] = "Brak ogłoszeń",
                ["views"] = "odsłon",
                // Profil
                ["MyProfile"] = "Mój profil",
                ["PersonalInfo"] = "Informacje osobowe",
                ["FirstName"] = "Imię",
                ["LastName"] = "Nazwisko",
                ["InterfaceSettings"] = "Ustawienia interfejsu",
                ["AdsPerPage"] = "Liczba ogłoszeń na stronie",
                ["SaveChanges"] = "Zapisz zmiany",
                ["Security"] = "Bezpieczeństwo",
                ["MyAds"] = "Moje ogłoszenia",
                ["Added"] = "Dodane",
                ["ViewMyAds"] = "Przeglądaj moje",
                ["ViewAllAds"] = "Przeglądaj wszystkie",
                ["AccountStatus"] = "Status konta",
                ["Status"] = "Status",
                ["Active"] = "Aktywne",
                ["Inactive"] = "Nieaktywne",
                ["Type"] = "Typ",
                ["Administrator"] = "Administrator",
                ["User"] = "Użytkownik",
                ["AccountSince"] = "Konto od",
                ["ProfileUpdated"] = "Profil zaktualizowany pomyślnie",
                // Logowanie
                ["LoginTitle"] = "Logowanie",
                ["UsernameOrEmail"] = "Nazwa użytkownika lub email",
                ["RememberMe"] = "Zapamiętaj mnie",
                ["LoginButton"] = "Zaloguj się",
                ["NoAccount"] = "Nie masz konta?",
                ["RegisterLink"] = "Zarejestruj się",
                // Rejestracja
                ["RegisterTitle"] = "Utwórz nowe konto",
                ["RegisterButton"] = "Zarejestruj się",
                ["HaveAccount"] = "Masz już konto?",
                ["LoginLink"] = "Zaloguj się",
                // Ogłoszenia
                ["AddNewAd"] = "Dodaj nowe ogłoszenie",
                ["ShortDescription"] = "Krótki opis",
                ["DetailedDescription"] = "Szczegółowy opis",
                ["AllowedTags"] = "Dozwolone tagi",
                ["SelectCategories"] = "Kategorie",
                ["Multimedia"] = "Multimedia",
                ["FilesToDownload"] = "Pliki do pobrania",
                ["MaxFiles"] = "Maksymalnie",
                ["Polish"] = "Polski",
                ["English"] = "English",
                ["German"] = "Deutsch",
                ["Default"] = "Domyślny",
                ["Dark"] = "Ciemny",
                ["Blue"] = "Niebieski",
                // Lista ogłoszeń i paginacja
                ["AllAdvertisements"] = "Wszystkie ogłoszenia",
                ["AdsFromCategory"] = "Ogłoszenia z kategorii",
                ["SearchResults"] = "Wyniki wyszukiwania",
                ["Author"] = "Autor",
                ["AddedOn"] = "Dodane",
                ["Views"] = "Odsłony",
                ["First"] = "Pierwsza",
                ["Previous"] = "Poprzednia",
                ["Next"] = "Następna",
                ["Last"] = "Ostatnia",
                ["NoAdsFound"] = "Brak ogłoszeń",
                ["NoAdsMessage"] = "Niestety nie znaleziono ogłoszeń. Spróbuj zmienić warunki wyszukiwania.",
                ["Manage"] = "Zarządzaj",
                ["Browse"] = "Przeglądaj",
                // Szczegóły ogłoszenia
                ["AdDetails"] = "Szczegóły ogłoszenia",
                ["DateAdded"] = "Data dodania",
                ["Attributes"] = "Atrybuty",
                ["Subcategories"] = "Podkategorie",
                ["Files"] = "Pliki",
                ["Download"] = "Pobierz",
                ["Contact"] = "Kontakt",
                ["ReportAd"] = "Zgłoś ogłoszenie",
                ["AdStatus"] = "Status",
                // Dodatkowe tytuły stron
                ["SearchResultsTitle"] = "Wyniki wyszukiwania",
                ["AdvancedSearchTitle"] = "Wyszukiwanie zaawansowane",
                ["NewsletterTitle"] = "Newsletter",
                ["AdminMessageTitle2"] = "Wiadomość Administratora",
                ["PrivacyPolicyTitle"] = "Polityka prywatności",
                ["HomeTitle"] = "Serwis ogłoszeń drobnych",
                ["DeleteAdTitle"] = "Usuń ogłoszenie",
                ["CategoriesTitle"] = "Kategorie",
                ["AdsFromCategoryTitle"] = "Ogłoszenia z kategorii",
                ["UsersManagementTitle"] = "Zarządzanie użytkownikami",
                ["ServiceSettingsTitle"] = "Ustawienia serwisu",
                ["ModerationTitle"] = "Moderacja ogłoszeń",
                ["ForbiddenWordsTitle"] = "Słowa zakazane",
                // Wyszukiwanie
                ["SearchResultsFor"] = "Wyniki wyszukiwania dla",
                ["SearchPlaceholder"] = "Wyszukaj ogłoszenia...",
                ["AndAllWords"] = "AND (wszystkie słowa)",
                ["OrAnyWord"] = "OR (dowolne słowo)",
                ["NotExclude"] = "NOT (bez słów)",
                ["AdvancedSearch"] = "Wyszukiwanie zaawansowane",
                ["Found"] = "Znaleziono",
                ["Advertisements2"] = "ogłoszeń",
                ["ViewDetails"] = "Zobacz szczegóły",
                ["NoResultsFound"] = "Nie znaleziono ogłoszeń spełniających kryteria wyszukiwania",
                ["ViewsCount"] = "odsłon",
                ["ActiveFilters"] = "Aktywne filtry",
                ["ClearFilters"] = "Wyczyść filtry",
                ["InCategory"] = "W kategorii",
                ["InCategories"] = "W kategoriach",
                ["AllCategories"] = "Wszystkie kategorie",
                ["FilterByCategory"] = "Filtruj po kategorii",
                ["SelectCategories"] = "Wybierz kategorie (możesz wybrać kilka)",
                // Wyszukiwanie zaawansowane
                ["SelectCategory"] = "Wybierz kategorię",
                ["CategoryAttributes"] = "Atrybuty kategorii",
                ["Any"] = "Dowolna",
                ["Yes"] = "Tak",
                ["No"] = "Nie",
                ["Select"] = "Wybierz",
                ["NoCategoryAttributes"] = "Ta kategoria nie ma zdefiniowanych atrybutów do wyszukiwania",
                ["SelectCategoryToSeeFilters"] = "Wybierz kategorię, aby zobaczyć dostępne filtry wyszukiwania",
                ["BackToBasicSearch"] = "← Powrót do wyszukiwania podstawowego",
                // Komunikaty
                ["ProfileUpdatedSuccessfully"] = "Profil zaktualizowany pomyślnie",
                ["PasswordChangedSuccessfully"] = "Hasło zmienione pomyślnie",
                ["PasswordResetEmailSent"] = "Jeśli konto istnieje, wiadomość z linkiem do resetowania hasła została wysłana",
                ["PasswordResetSuccessfully"] = "Hasło zostało zresetowane. Możesz się teraz zalogować",
                ["InvalidResetToken"] = "Nieprawidłowy token resetowania hasła",
                ["ResetTokenExpired"] = "Token resetowania hasła wygasł",
                ["MessageUpdated"] = "Wiadomość zaktualizowana",
                ["UserStatusUpdated"] = "Status użytkownika zaktualizowany pomyślnie",
                ["CategoryCreated"] = "Kategoria utworzona pomyślnie",
                ["CategoryNameRequired"] = "Nazwa kategorii jest wymagana",
                ["SettingsUpdated"] = "Ustawienia zaktualizowane pomyślnie",
                ["ReportApproved"] = "Zgłoszenie zaakceptowane, ogłoszenie usunięte",
                ["ReportRejected"] = "Zgłoszenie odrzucone"
            },
            ["en"] = new Dictionary<string, string>
            {
                ["Home"] = "Home",
                ["Advertisements"] = "Advertisements",
                ["AddAdvertisement"] = "Add Advertisement",
                ["Categories"] = "Categories",
                ["Search"] = "Search",
                ["Login"] = "Login",
                ["Register"] = "Register",
                ["Logout"] = "Logout",
                ["Profile"] = "Profile",
                ["AdminPanel"] = "Admin Panel",
                ["Title"] = "Title",
                ["Description"] = "Description",
                ["Price"] = "Price",
                ["Category"] = "Category",
                ["CreatedAt"] = "Created At",
                ["ViewCount"] = "Views",
                ["Edit"] = "Edit",
                ["Delete"] = "Delete",
                ["Details"] = "Details",
                ["Save"] = "Save",
                ["Cancel"] = "Cancel",
                ["Back"] = "Back",
                ["Submit"] = "Submit",
                ["Username"] = "Username",
                ["Email"] = "Email",
                ["Password"] = "Password",
                ["ConfirmPassword"] = "Confirm Password",
                ["ForgotPassword"] = "Forgot Password?",
                ["ResetPassword"] = "Reset Password",
                ["ChangePassword"] = "Change Password",
                ["Welcome"] = "Welcome to the classifieds service!",
                ["LatestAds"] = "Latest Advertisements",
                ["NoResults"] = "No results",
                ["Loading"] = "Loading...",
                ["Error"] = "Error",
                ["Success"] = "Success",
                ["Users"] = "Users",
                ["Moderation"] = "Moderation",
                ["Settings"] = "Settings",
                ["Newsletter"] = "Newsletter",
                ["AdminMessage"] = "Admin Message",
                ["ForbiddenWords"] = "Forbidden Words",
                ["Theme"] = "Theme",
                ["Language"] = "Language",
                ["PageSize"] = "Items per page",
                // Homepage
                ["ClassifiedsService"] = "Classifieds Service",
                ["SearchingOrSelling"] = "Looking for something? Want to sell? Welcome to our service!",
                ["SearchAds"] = "Search ads...",
                ["BrowseAll"] = "Browse all",
                ["EasyAdding"] = "Easy adding",
                ["EasyAddingDesc"] = "Add an ad in just a few minutes",
                ["FastSearch"] = "Fast search",
                ["FastSearchDesc"] = "Find what you're looking for in seconds",
                ["CategoriesFeature"] = "Categories",
                ["CategoriesDesc"] = "Clear advertisement categories",
                ["SecureTransaction"] = "Secure transaction",
                ["SecureTransactionDesc"] = "Direct contact with the seller",
                ["AdminMessageTitle"] = "Message from administration",
                ["NoAds"] = "No advertisements",
                ["views"] = "views",
                // Profile
                ["MyProfile"] = "My profile",
                ["PersonalInfo"] = "Personal information",
                ["FirstName"] = "First name",
                ["LastName"] = "Last name",
                ["InterfaceSettings"] = "Interface settings",
                ["AdsPerPage"] = "Ads per page",
                ["SaveChanges"] = "Save changes",
                ["Security"] = "Security",
                ["MyAds"] = "My advertisements",
                ["Added"] = "Added",
                ["ViewMyAds"] = "View my ads",
                ["ViewAllAds"] = "View all ads",
                ["AccountStatus"] = "Account status",
                ["Status"] = "Status",
                ["Active"] = "Active",
                ["Inactive"] = "Inactive",
                ["Type"] = "Type",
                ["Administrator"] = "Administrator",
                ["User"] = "User",
                ["AccountSince"] = "Account since",
                ["ProfileUpdated"] = "Profile updated successfully",
                // Login
                ["LoginTitle"] = "Login",
                ["UsernameOrEmail"] = "Username or email",
                ["RememberMe"] = "Remember me",
                ["LoginButton"] = "Log in",
                ["NoAccount"] = "Don't have an account?",
                ["RegisterLink"] = "Register",
                // Register
                ["RegisterTitle"] = "Create new account",
                ["RegisterButton"] = "Sign up",
                ["HaveAccount"] = "Already have an account?",
                ["LoginLink"] = "Log in",
                // Advertisements
                ["AddNewAd"] = "Add new advertisement",
                ["ShortDescription"] = "Short description",
                ["DetailedDescription"] = "Detailed description",
                ["AllowedTags"] = "Allowed tags",
                ["SelectCategories"] = "Categories",
                ["Multimedia"] = "Multimedia",
                ["FilesToDownload"] = "Files to download",
                ["MaxFiles"] = "Maximum",
                ["Polish"] = "Polish",
                ["English"] = "English",
                ["German"] = "German",
                ["Default"] = "Default",
                ["Dark"] = "Dark",
                ["Blue"] = "Blue",
                // Ads list and pagination
                ["AllAdvertisements"] = "All advertisements",
                ["AdsFromCategory"] = "Ads from category",
                ["SearchResults"] = "Search results",
                ["Author"] = "Author",
                ["AddedOn"] = "Added",
                ["Views"] = "Views",
                ["First"] = "First",
                ["Previous"] = "Previous",
                ["Next"] = "Next",
                ["Last"] = "Last",
                ["NoAdsFound"] = "No advertisements",
                ["NoAdsMessage"] = "Unfortunately, no ads were found. Try changing the search criteria.",
                ["Manage"] = "Manage",
                ["Browse"] = "Browse",
                // Ad details
                ["AdDetails"] = "Advertisement details",
                ["DateAdded"] = "Date added",
                ["Attributes"] = "Attributes",
                ["Subcategories"] = "Subcategories",
                ["Files"] = "Files",
                ["Download"] = "Download",
                ["Contact"] = "Contact",
                ["ReportAd"] = "Report ad",
                ["AdStatus"] = "Status",
                // Additional page titles
                ["SearchResultsTitle"] = "Search Results",
                ["AdvancedSearchTitle"] = "Advanced Search",
                ["NewsletterTitle"] = "Newsletter",
                ["AdminMessageTitle2"] = "Administrator Message",
                ["PrivacyPolicyTitle"] = "Privacy Policy",
                ["HomeTitle"] = "Classifieds Service",
                ["DeleteAdTitle"] = "Delete Advertisement",
                ["CategoriesTitle"] = "Categories",
                ["AdsFromCategoryTitle"] = "Ads from Category",
                ["UsersManagementTitle"] = "User Management",
                ["ServiceSettingsTitle"] = "Service Settings",
                ["ModerationTitle"] = "Advertisement Moderation",
                ["ForbiddenWordsTitle"] = "Forbidden Words",
                // Search
                ["SearchResultsFor"] = "Search results for",
                ["SearchPlaceholder"] = "Search ads...",
                ["AndAllWords"] = "AND (all words)",
                ["OrAnyWord"] = "OR (any word)",
                ["NotExclude"] = "NOT (exclude words)",
                ["AdvancedSearch"] = "Advanced Search",
                ["Found"] = "Found",
                ["Advertisements2"] = "advertisements",
                ["ViewDetails"] = "View details",
                ["NoResultsFound"] = "No ads found matching your search criteria",
                ["ViewsCount"] = "views",
                ["ActiveFilters"] = "Active Filters",
                ["ClearFilters"] = "Clear Filters",
                ["InCategory"] = "In Category",
                ["InCategories"] = "In Categories",
                ["AllCategories"] = "All Categories",
                ["FilterByCategory"] = "Filter by Category",
                ["SelectCategories"] = "Select categories (you can select multiple)",
                // Advanced search
                ["SelectCategory"] = "Select category",
                ["CategoryAttributes"] = "Category attributes",
                ["Any"] = "Any",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["Select"] = "Select",
                ["NoCategoryAttributes"] = "This category has no defined search attributes",
                ["SelectCategoryToSeeFilters"] = "Select a category to see available search filters",
                ["BackToBasicSearch"] = "← Back to basic search",
                // Messages
                ["ProfileUpdatedSuccessfully"] = "Profile updated successfully",
                ["PasswordChangedSuccessfully"] = "Password changed successfully",
                ["PasswordResetEmailSent"] = "If the account exists, a password reset link has been sent",
                ["PasswordResetSuccessfully"] = "Password has been reset. You can now log in",
                ["InvalidResetToken"] = "Invalid password reset token",
                ["ResetTokenExpired"] = "Password reset token has expired",
                ["MessageUpdated"] = "Message updated",
                ["UserStatusUpdated"] = "User status updated successfully",
                ["CategoryCreated"] = "Category created successfully",
                ["CategoryNameRequired"] = "Category name is required",
                ["SettingsUpdated"] = "Settings updated successfully",
                ["ReportApproved"] = "Report approved, advertisement deleted",
                ["ReportRejected"] = "Report rejected"
            },
            ["de"] = new Dictionary<string, string>
            {
                ["Home"] = "Startseite",
                ["Advertisements"] = "Anzeigen",
                ["AddAdvertisement"] = "Anzeige hinzufügen",
                ["Categories"] = "Kategorien",
                ["Search"] = "Suchen",
                ["Login"] = "Anmelden",
                ["Register"] = "Registrieren",
                ["Logout"] = "Abmelden",
                ["Profile"] = "Profil",
                ["AdminPanel"] = "Admin-Panel",
                ["Title"] = "Titel",
                ["Description"] = "Beschreibung",
                ["Price"] = "Preis",
                ["Category"] = "Kategorie",
                ["CreatedAt"] = "Erstellt am",
                ["ViewCount"] = "Ansichten",
                ["Edit"] = "Bearbeiten",
                ["Delete"] = "Löschen",
                ["Details"] = "Details",
                ["Save"] = "Speichern",
                ["Cancel"] = "Abbrechen",
                ["Back"] = "Zurück",
                ["Submit"] = "Absenden",
                ["Username"] = "Benutzername",
                ["Email"] = "E-Mail",
                ["Password"] = "Passwort",
                ["ConfirmPassword"] = "Passwort bestätigen",
                ["ForgotPassword"] = "Passwort vergessen?",
                ["ResetPassword"] = "Passwort zurücksetzen",
                ["ChangePassword"] = "Passwort ändern",
                ["Welcome"] = "Willkommen bei den Kleinanzeigen!",
                ["LatestAds"] = "Neueste Anzeigen",
                ["NoResults"] = "Keine Ergebnisse",
                ["Loading"] = "Wird geladen...",
                ["Error"] = "Fehler",
                ["Success"] = "Erfolg",
                ["Users"] = "Benutzer",
                ["Moderation"] = "Moderation",
                ["Settings"] = "Einstellungen",
                ["Newsletter"] = "Newsletter",
                ["AdminMessage"] = "Admin-Nachricht",
                ["ForbiddenWords"] = "Verbotene Wörter",
                ["Theme"] = "Design",
                ["Language"] = "Sprache",
                ["PageSize"] = "Elemente pro Seite",
                // Startseite
                ["ClassifiedsService"] = "Kleinanzeigen-Service",
                ["SearchingOrSelling"] = "Suchen Sie etwas? Möchten Sie etwas verkaufen? Willkommen bei unserem Service!",
                ["SearchAds"] = "Anzeigen suchen...",
                ["BrowseAll"] = "Alle durchsuchen",
                ["EasyAdding"] = "Einfaches Hinzufügen",
                ["EasyAddingDesc"] = "Fügen Sie eine Anzeige in nur wenigen Minuten hinzu",
                ["FastSearch"] = "Schnelle Suche",
                ["FastSearchDesc"] = "Finden Sie, was Sie suchen, in Sekunden",
                ["CategoriesFeature"] = "Kategorien",
                ["CategoriesDesc"] = "Übersichtliche Anzeigenkategorien",
                ["SecureTransaction"] = "Sichere Transaktion",
                ["SecureTransactionDesc"] = "Direkter Kontakt mit dem Verkäufer",
                ["AdminMessageTitle"] = "Nachricht von der Verwaltung",
                ["NoAds"] = "Keine Anzeigen",
                ["views"] = "Ansichten",
                // Profil
                ["MyProfile"] = "Mein Profil",
                ["PersonalInfo"] = "Persönliche Informationen",
                ["FirstName"] = "Vorname",
                ["LastName"] = "Nachname",
                ["InterfaceSettings"] = "Oberflächeneinstellungen",
                ["AdsPerPage"] = "Anzeigen pro Seite",
                ["SaveChanges"] = "Änderungen speichern",
                ["Security"] = "Sicherheit",
                ["MyAds"] = "Meine Anzeigen",
                ["Added"] = "Hinzugefügt",
                ["ViewMyAds"] = "Meine Anzeigen anzeigen",
                ["ViewAllAds"] = "Alle Anzeigen anzeigen",
                ["AccountStatus"] = "Kontostatus",
                ["Status"] = "Status",
                ["Active"] = "Aktiv",
                ["Inactive"] = "Inaktiv",
                ["Type"] = "Typ",
                ["Administrator"] = "Administrator",
                ["User"] = "Benutzer",
                ["AccountSince"] = "Konto seit",
                ["ProfileUpdated"] = "Profil erfolgreich aktualisiert",
                // Anmeldung
                ["LoginTitle"] = "Anmelden",
                ["UsernameOrEmail"] = "Benutzername oder E-Mail",
                ["RememberMe"] = "Angemeldet bleiben",
                ["LoginButton"] = "Anmelden",
                ["NoAccount"] = "Haben Sie kein Konto?",
                ["RegisterLink"] = "Registrieren",
                // Registrierung
                ["RegisterTitle"] = "Neues Konto erstellen",
                ["RegisterButton"] = "Registrieren",
                ["HaveAccount"] = "Haben Sie bereits ein Konto?",
                ["LoginLink"] = "Anmelden",
                // Anzeigen
                ["AddNewAd"] = "Neue Anzeige hinzufügen",
                ["ShortDescription"] = "Kurze Beschreibung",
                ["DetailedDescription"] = "Detaillierte Beschreibung",
                ["AllowedTags"] = "Erlaubte Tags",
                ["SelectCategories"] = "Kategorien",
                ["Multimedia"] = "Multimedia",
                ["FilesToDownload"] = "Dateien zum Herunterladen",
                ["MaxFiles"] = "Maximum",
                ["Polish"] = "Polnisch",
                ["English"] = "Englisch",
                ["German"] = "Deutsch",
                ["Default"] = "Standard",
                ["Dark"] = "Dunkel",
                ["Blue"] = "Blau",
                // Anzeigenliste und Paginierung
                ["AllAdvertisements"] = "Alle Anzeigen",
                ["AdsFromCategory"] = "Anzeigen aus Kategorie",
                ["SearchResults"] = "Suchergebnisse",
                ["Author"] = "Autor",
                ["AddedOn"] = "Hinzugefügt",
                ["Views"] = "Ansichten",
                ["First"] = "Erste",
                ["Previous"] = "Vorherige",
                ["Next"] = "Nächste",
                ["Last"] = "Letzte",
                ["NoAdsFound"] = "Keine Anzeigen",
                ["NoAdsMessage"] = "Leider wurden keine Anzeigen gefunden. Versuchen Sie, die Suchkriterien zu ändern.",
                ["Manage"] = "Verwalten",
                ["Browse"] = "Durchsuchen",
                // Anzeigendetails
                ["AdDetails"] = "Anzeigendetails",
                ["DateAdded"] = "Hinzugefügt am",
                ["Attributes"] = "Attribute",
                ["Subcategories"] = "Unterkategorien",
                ["Files"] = "Dateien",
                ["Download"] = "Herunterladen",
                ["Contact"] = "Kontakt",
                ["ReportAd"] = "Anzeige melden",
                ["AdStatus"] = "Status",
                // Zusätzliche Seitentitel
                ["SearchResultsTitle"] = "Suchergebnisse",
                ["AdvancedSearchTitle"] = "Erweiterte Suche",
                ["NewsletterTitle"] = "Newsletter",
                ["AdminMessageTitle2"] = "Administrator-Nachricht",
                ["PrivacyPolicyTitle"] = "Datenschutzrichtlinie",
                ["HomeTitle"] = "Kleinanzeigen-Service",
                ["DeleteAdTitle"] = "Anzeige löschen",
                ["CategoriesTitle"] = "Kategorien",
                ["AdsFromCategoryTitle"] = "Anzeigen aus Kategorie",
                ["UsersManagementTitle"] = "Benutzerverwaltung",
                ["ServiceSettingsTitle"] = "Serviceeinstellungen",
                ["ModerationTitle"] = "Anzeigenmoderation",
                ["ForbiddenWordsTitle"] = "Verbotene Wörter",
                // Suche
                ["SearchResultsFor"] = "Suchergebnisse für",
                ["SearchPlaceholder"] = "Anzeigen suchen...",
                ["AndAllWords"] = "UND (alle Wörter)",
                ["OrAnyWord"] = "ODER (beliebiges Wort)",
                ["NotExclude"] = "NICHT (ohne Wörter)",
                ["AdvancedSearch"] = "Erweiterte Suche",
                ["Found"] = "Gefunden",
                ["Advertisements2"] = "Anzeigen",
                ["ViewDetails"] = "Details anzeigen",
                ["NoResultsFound"] = "Keine Anzeigen gefunden, die Ihren Suchkriterien entsprechen",
                ["ViewsCount"] = "Ansichten",
                ["ActiveFilters"] = "Aktive Filter",
                ["ClearFilters"] = "Filter löschen",
                ["InCategory"] = "In Kategorie",
                ["InCategories"] = "In Kategorien",
                ["AllCategories"] = "Alle Kategorien",
                ["FilterByCategory"] = "Nach Kategorie filtern",
                ["SelectCategories"] = "Kategorien auswählen (mehrere möglich)",
                // Erweiterte Suche
                ["SelectCategory"] = "Kategorie auswählen",
                ["CategoryAttributes"] = "Kategorieattribute",
                ["Any"] = "Beliebig",
                ["Yes"] = "Ja",
                ["No"] = "Nein",
                ["Select"] = "Auswählen",
                ["NoCategoryAttributes"] = "Diese Kategorie hat keine definierten Suchattribute",
                ["SelectCategoryToSeeFilters"] = "Wählen Sie eine Kategorie aus, um verfügbare Suchfilter anzuzeigen",
                ["InvalidResetToken"] = "Ungültiger Passwort-Reset-Token",
                ["ResetTokenExpired"] = "Passwort-Reset-Token ist abgelaufen",
                ["MessageUpdated"] = "Nachricht aktualisiert",
                ["UserStatusUpdated"] = "Benutzerstatus erfolgreich aktualisiert",
                ["CategoryCreated"] = "Kategorie erfolgreich erstellt",
                ["CategoryNameRequired"] = "Kategoriename ist erforderlich",
                ["SettingsUpdated"] = "Einstellungen erfolgreich aktualisiert",
                ["ReportApproved"] = "Bericht genehmigt, Anzeige gelöscht",
                ["ReportRejected"] = "Bericht abgelehnt",
                ["PasswordResetEmailSent"] = "Wenn das Konto existiert, wurde ein Link zum Zurücksetzen des Passworts gesendet",
                ["PasswordResetSuccessfully"] = "Passwort wurde zurückgesetzt. Sie können sich jetzt anmelden"
            }
        };

        public LocalizationService(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public string Get(string key, string? language = null)
        {
            // Get language from parameter, session, or default to Polish
            var currentLanguage = language 
                ?? _httpContextAccessor.HttpContext?.Session.GetString("Language") 
                ?? "pl";

            if (_translations.ContainsKey(currentLanguage) && 
                _translations[currentLanguage].ContainsKey(key))
            {
                return _translations[currentLanguage][key];
            }
            return key; // Fallback to key if translation not found
        }
    }
}
